### ISSUE TITLE
loading builtin textures

### ISSUE THREAD

**Issue by Sigma88** [HappyFaceIndustries/KopernicusExpansion#1]
would it be possible to load the Eve ocean texture from the built in Eve Scaled Version texture?

the shape of the ocean is saved in the alpha channel

it's not a major issue, more like a suggestion :)

**Comment by HappyFaceIndustries** [comment]
Are you talking about the example config Eve?

**Comment by Sigma88** [comment]
yes, I've seen that for the glowing oceans you use a texture which is included in the zip for the examples

emissiveMap = KopernicusExpansionExamples/Data/EveOcean

would it be possible to load that from the alpha channel of the stock texture?

to be clear, I am talking of eve just because that is the example, but the feature would be applicable to all planets with an ocean of course

**Comment by HappyFaceIndustries** [comment]
It would be possible, but I didn't because it was too pixelated. I'm using a higher res texture, which I also blurred a bit to make the glow less harsh.

**Comment by Sigma88** [comment]
I just thought it could have been useful to have the option.

Closing this since I've got my answer :+1:
